- state/store.go
> missing a change

- blockchain/wire.go
- consensus/types/wire.go
- consensus/wire.go
- types/wire.go
http://jira.bianjie.ai/browse/IRISHUB-304
> Hotfix: IRISHUB-304

- blockchain/store.go
- consensus/replay_test.go
- state/services.go
> Add reteat last block interface for block store

- abci/types/util.go
- cmd/tendermint/commands/run_node.go
- config/config.go
- config/toml.go
- consensus/replay.go
- consensus/replay_file.go
- consensus/state.go
- node/node.go
- state/execution.go
- state/state.go
- state/validation.go
> R4R: Add our changes to v0.27.3

- cmd/tendermint/commands/run_node.go
> R4R: Improve replay_height description

- blockchain/store.go
- state/execution.go
- state/services.go
- state/state.go
- state/store.go
> R4R: Add reteat last block and store preState

- consensus/replay.go
> R4R: Use goroutine exit instead of process exit

- evidence/store.go
closes: https://github.com/irisnet/irishub/issues/999
> R4R: Fix bug in including evidece into block

- consensus/replay.go
- state/execution.go
https://github.com/irisnet/tendermint/pull/31
https://github.com/irisnet/tendermint/pull/32
> R4R: Fix replay bug

- consensus/reactor_test.go
- evidence/pool.go
- evidence/store.go
- state/execution.go
- state/services.go
- state/validation.go
> R4R: Avoid one evidence being committed multiple times

- lite/base_verifier.go
- lite/commit.go
- lite/dbprovider.go
- lite/doc.go
- lite/dynamic_verifier.go
- lite/dynamic_verifier_test.go
- lite/errors/errors.go
- lite/multiprovider.go
- lite/provider.go
- types/block.go
- types/validator_set.go
Merge https://github.com/tendermint/tendermint/pull/3171
> R4R: Fix DynamicVerifier for large validator set changes

- consensus/metrics.go
- consensus/state.go
- state/execution.go
- state/metrics.go
- state/validation.go
closes: https://github.com/irisnet/irishub/issues/1188
> R4R: Add consensus failure to metrics

- rpc/core/tx.go
- state/txindex/indexer.go
- state/txindex/kv/kv.go
- state/txindex/null/null.go
Ref: https://github.com/irisnet/irishub/issues/1200
> R4R: Optimize txs search

- privval/remote_signer.go
A new tag `v0.27.3-iris6` should be created and then used in `irishub`. This change is fully compatible with everything else, it just patches the remote signer so that it works with the latest KMS.
@haifengxi
> Patch remote signer to work with the KMS

- consensus/state.go
- consensus/types/round_state.go
Closes: https://github.com/irisnet/irishub/issues/1333
Rf: https://github.com/tendermint/tendermint/pull/3197
> R4R: Fix consensus round issue

- mempool/mempool.go
Related PR: https://github.com/tendermint/tendermint/pull/3036
Related issue: https://github.com/tendermint/tendermint/issues/3035
> R4R: Add latest tx to the back of cache list

- mempool/reactor.go
- p2p/conn_set.go
- p2p/dummy/peer.go
- p2p/peer.go
- p2p/peer_set_test.go
- p2p/peer_test.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
- p2p/transport.go
closes: https://github.com/irisnet/irishub/issues/1202
https://github.com/tendermint/tendermint/issues/2046
> R4R: Fix goroutine leak

- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
Cherry pick from https://github.com/tendermint/tendermint/pull/3232
> R4R: fix infinite loop in addrbook

- version/version.go
> R4R: Update version to 0.27.4 on master

- consensus/replay_test.go
- consensus/wal.go
- consensus/wal_test.go
- libs/autofile/group.go
- node/node_test.go
- p2p/test_util.go
- privval/client.go
Resolves: https://github.com/irisnet/irishub/issues/1438
> R4R:  Fix non deterministic test failures

- consensus/replay.go
- consensus/replay_file.go
- node/node.go
Resolves: https://github.com/irisnet/irishub/issues/1440
> R4R: Start eventBus and indexerService before first block

- crypto/multisig/threshold_pubkey.go
- crypto/multisig/threshold_pubkey_test.go
Resovles: https://github.com/irisnet/irishub/issues/1466, https://github.com/irisnet/irishub/issues/1432
> R4R: Refactor PubKeyMultisigThreshold to support multisig

- libs/db/c_level_db.go
- libs/db/debug_db.go
- libs/db/go_level_db.go
- libs/db/mem_batch.go
- libs/db/prefix_db.go
- libs/db/remotedb/grpcdb/server.go
- libs/db/remotedb/remotedb.go
- libs/db/types.go
- lite/dbprovider.go
- state/txindex/kv/kv.go
Resolves: https://github.com/irisnet/irishub/issues/1451
> R4R: Close WriteBatch to prevent memory leak

- libs/log/tmfmt_logger.go
Resolves: https://github.com/irisnet/irishub/issues/1651
> R4R: Fix year format

- consensus/metrics.go
- mempool/metrics.go
- node/node.go
- p2p/metrics.go
- state/metrics.go
Resolves: https://github.com/irisnet/irishub/issues/1660
> R4R: Add "chain_id" label for all metrics

- rpc/core/pipe.go
- rpc/core/pipe_test.go
Resolves: https://github.com/irisnet/irishub/issues/1665
> R4R: Return maxPerPage if per_page is greater than max

- consensus/replay.go
- consensus/state.go
- consensus/wal.go
- libs/fail/fail.go
- privval/file.go
Resolves: https://github.com/irisnet/irishub/issues/1668
> R4R: Better errors and new fail point

- node/node.go
- p2p/dummy/peer.go
- p2p/node_info.go
- p2p/peer.go
- p2p/peer_set_test.go
- p2p/peer_test.go
- p2p/pex/addrbook.go
- p2p/pex/addrbook_test.go
- p2p/pex/pex_reactor.go
- p2p/pex/pex_reactor_test.go
- p2p/switch.go
- p2p/switch_test.go
- p2p/test_util.go
- p2p/transport.go
- rpc/core/consensus.go
Resolves: https://github.com/irisnet/irishub/issues/1679, https://github.com/irisnet/irishub/issues/1403
> R4R: Improve p2p connection

- consensus/common_test.go
- consensus/state.go
Resolves: https://github.com/irisnet/irishub/issues/1646
> R4R: Reset triggered timeout precommit

- consensus/wal.go
Resolves: https://github.com/irisnet/irishub/issues/1647
> R4R: Flush wal on stop

- libs/pubsub/pubsub.go
- p2p/switch.go
- p2p/switch_test.go
Resolves: https://github.com/irisnet/irishub/issues/1648
> R4R: Fix dirty data in peerset

- p2p/conn/secret_connection.go
- p2p/conn/secret_connection_test.go
Resolves: https://github.com/irisnet/irishub/issues/1650
> R4R: Check all zeroes for secret connection

- p2p/switch.go
- p2p/switch_test.go
- p2p/transport.go
Resolves: https://github.com/irisnet/irishub/issues/1649
> R4R: Do not panic when filter times out

- consensus/replay.go
Resolves: https://github.com/irisnet/irishub/issues/1554
> R4R: Log replay with state module

- blockchain/pool.go
Resolves: https://github.com/irisnet/irishub/issues/1692
> R4R: Fix pool timer leak bug

- libs/db/remotedb/grpcdb/server.go
Resolves: https://github.com/irisnet/irishub/issues/1693
> R4R: Close Iterator in RemoteDB

- lite/proxy/proxy.go
- lite/proxy/query.go
- lite/proxy/wrapper.go
Resolves: https://github.com/irisnet/irishub/issues/1697
> R4R: Fix lite client proxy endpoints

- blockchain/pool.go
- blockchain/pool_test.go
Resolves: https://github.com/irisnet/irishub/issues/1702
> R4R: Update the maxHeight when a peer is removed

- config/config.go
- config/toml.go
- docs/tendermint-core/configuration.md
- mempool/bench_test.go
- mempool/cache_test.go
- mempool/mempool.go
- mempool/mempool_test.go
- mempool/metrics.go
- mempool/reactor.go
- mempool/reactor_test.go
- p2p/mock/peer.go
- rpc/client/rpc_test.go
- rpc/core/mempool.go
- rpc/core/types/responses.go
- state/services.go
Resolves: https://github.com/irisnet/irishub/issues/1714, https://github.com/irisnet/irishub/issues/1703
> R4R:  Update mempool to v0.31.2

- rpc/lib/client/http_client.go
Resolves: https://github.com/irisnet/irishub/issues/1704
> R4R: Client disable compression

- p2p/pex/pex_reactor.go
Resolves: https://github.com/irisnet/irishub/issues/1666
> R4R: Only log "Reached max attempts to dial" once

- crypto/multisig/multisignature.go
- crypto/multisig/threshold_pubkey_test.go
Resolves: https://github.com/irisnet/irishub/issues/1918
> R4R: Improve error message returned from AddSignatureFromPubKey

- consensus/reactor.go
Resolves: https://github.com/irisnet/irishub/issues/1921
> R4R: Exit if SwitchToConsensus fails

- p2p/conn/secret_connection.go
> Cherry pick p2p bug fix to develop

- Gopkg.lock
- crypto/multisig/threshold_pubkey.go
- p2p/conn/secret_connection.go
- p2p/conn/secret_connection_test.go
- p2p/transport.go
- version/version.go
Resolves: https://github.com/tendermint/tendermint/issues/4030
Cherry pick: https://github.com/tendermint/tendermint/commit/5c9b5cfa1d3913dc4b17641b54e8ec835a089b4a
Update version to v0.31.2
> R4R: Only allow ed25519 pubkeys when connecting

- consensus/reactor.go
- consensus/reactor_test.go
- consensus/replay_test.go
- consensus/state.go
- consensus/wal.go
- consensus/wal_generator.go
- consensus/wal_test.go
- crypto/merkle/simple_proof.go
- crypto/merkle/simple_proof_test.go
- types/params.go
- types/part_set.go
- types/part_set_test.go
- types/vote_set.go
- version/version.go
Ref: https://github.com/tendermint/tendermint/compare/v0.31.10...v0.31.11
> R4R: Cherry pick security patch from tendermint v0.31.11

- consensus/byzantine_test.go
- consensus/reactor.go
- consensus/reactor_test.go
- consensus/replay_test.go
- consensus/state.go
- consensus/state_test.go
- consensus/wal.go
- consensus/wal_generator.go
- consensus/wal_test.go
- crypto/merkle/simple_proof.go
- crypto/merkle/simple_proof_test.go
- go.mod
- types/params.go
- types/part_set.go
- types/part_set_test.go
- types/vote_set.go
> R4R: Cherry pick security patch

- version/version.go
> R4R: Update tendermint version

- consensus/reactor.go
Resolves: https://github.com/irisnet/irishub/issues/2070
> R4R: Do not panic on querying blockMeta

- version/version.go
> Update version to v0.32.1

- consensus/reactor.go
- version/version.go
> R4R: Release v0.32.1
